services:
  fastapi_prod:
    build: .
    container_name: bookapi-app
    networks:
      - hng-network
    restart: unless-stopped
    ports:
      - 8000:8000
    working_dir: /app 

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - hng-network

networks:
  hng-network:
    driver: bridge