services:
  app_prod:
    image: stage-two-prod:latest
    command: ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
    container_name: app_prod
    networks:
      - hng-network
    restart: unless-stopped
    ports:
      - 8000:8000
    working_dir: /app 
    volumes:
      - .env:/app/.env

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - hng-network

networks:
  hng-network:
    driver: bridge